import Header from '@/components/Header';
import Section from '@/components/Section';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import Image from 'next/image';
import { useCallback, useEffect, useState } from 'react';
import { SiGithub, SiGitlab, SiLinkedin, SiTelegram } from 'react-icons/si';
import tw, { styled } from 'twin.macro';

const Technologies = dynamic(() => import('@/features/Technologies'), {
  ssr: false,
  loading: () => <p>Loading...</p>,
});

const ResumeGenerator = dynamic(() => import('@/features/ResumeGenerator'), {
  ssr: false,
  loading: () => <p>Loading...</p>,
});

const RecentProjects = dynamic(() => import('@/features/RecentProjects'), {
  ssr: false,
  loading: () => <p>Loading...</p>,
});
const ContactForm = dynamic(() => import('@/features/ContactForm'), {
  ssr: false,
  loading: () => <p>Loading...</p>,
});

const Root = tw.div`bg-slate-50 scroll-smooth dark:(bg-gradient-to-b from-black to-blue-900 text-white)`;

const SocialLink = tw.a`inline-block pr-4 hover:text-zinc-400 dark:(text-white hover:text-zinc-300)`;

const HeroSection = tw(Section)`md:flex-row`;

const OddSection = tw(Section)`bg-transparent`;

const SectionHeading = tw.h2`text-2xl font-bold drop-shadow	p-2`;

const HireMeHeading = styled.h1`
  font-size: 60px;
  font-weight: 600;
  padding-bottom: 2rem;
  color: #e0d6e9;
  text-shadow: 2px 2px 0px #957dad, 4px 4px 0px #ee4b2b, 6px 6px 0px #00c2cb,
    8px 8px 0px #ff7f50, 10px 10px 0px #553c9a;
`;

const App = () => {
  const [visibleSection, setVisibleSection] = useState('home');

  useEffect(() => {}, [visibleSection]);

  const handleChangeVisibleSection = useCallback((section: string) => {
    setVisibleSection(section);
  }, []);

  return (
    <Root>
      <Head>
        <title>Luke&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header activeSection={visibleSection} />
      <main>
        <HeroSection name="home" setVisible={handleChangeVisibleSection}>
          <div tw="h-36 w-36 self-center overflow-hidden container">
            <Image
              width={250}
              height={400}
              tw="border-8 border-white rounded-full"
              alt="Picture of the author"
              src="/images/photo.jpeg"
            />
          </div>
          <div tw="pb-5 px-4 self-center">
            <h1 tw="text-4xl lg:text-6xl">
              Hi, <br />I am <span tw="font-bold">L</span>uke
            </h1>
            <h2 tw="text-2xl lg:text-4xl leading-10">
              I like to think of myself as a{' '}
              {/* <del tw="italic font-bold ">problem-solver</del>{' '} */}
              <span tw="italic font-bold pl-1 pr-2 before:block before:absolute before:-inset-1 before:-skew-y-3 before:bg-purple-700 relative inline-block">
                <span tw="relative text-white">solution-finder</span>
              </span>
            </h2>

            <p tw="py-5">
              I am proficient at using computers.{' '}
              <span
                role="img"
                aria-label="Emoji grinning Face with Sweat"
                aria-hidden={true}
              >
                😅
              </span>
            </p>

            <div className="flex py-5 ">
              <SocialLink tw="text-2xl" href="https://github.com/born2bewild">
                <SiGithub size={40} />
              </SocialLink>
              <SocialLink href="https://gitlab.com/lukasz.wawrzyniak">
                <SiGitlab size={40} />
              </SocialLink>
              <SocialLink href="https://www.linkedin.com/in/lukaszwawrzyniak/">
                <SiLinkedin size={40} />
              </SocialLink>
              <SocialLink href="https://t.me/luke_wawrzyniak/">
                <SiTelegram size={40} />
              </SocialLink>
            </div>
          </div>
        </HeroSection>

        <OddSection name="about" setVisible={handleChangeVisibleSection}>
          <div tw=" align-middle justify-center">
            <SectionHeading>About me</SectionHeading>
            <div tw="container mx-auto my-auto align-middle prose dark:prose-invert">
              <h3>Passionate Software Engineer</h3>
              <p>
                With 10+ years of experience in developing innovative solutions
                using cutting-edge technologies. Skilled at writing clear,
                concise code that is easy to maintain and troubleshoot.
                Experienced in working with both small and large teams across
                multiple projects and companies.
              </p>
              <p>
                Excited by and knowledgeable about many vital IT technologies.
                Always challenging myself to grow as a developer and find ways
                to solve difficult problems. With the capacity to adapt and
                learn fast. Able to work independently of remote locations or in
                office environments as needed by the company.
              </p>
              <p>
                Throughout my career, I have honed my skills in developing
                robust and scalable web applications, building efficient APIs,
                and crafting intuitive user interfaces. I have a keen eye for
                detail and pride myself on delivering high-quality code that is
                both efficient and maintainable.
              </p>
              <p>
                My extensive knowledge of NodeJS, PHP, Python, and React has
                allowed me to take on a variety of challenging projects and
                deliver exceptional results. Whether it&apos;s building custom
                CMS systems, developing eCommerce platforms, or creating
                data-driven applications, I am passionate about taking on new
                challenges and finding creative solutions to complex problems.
              </p>
              <p>
                In addition to my technical skills, I am a team player who
                thrives in collaborative environments. I enjoy working closely
                with designers, project managers, and stakeholders to ensure
                that every project meets the highest standards of quality and
                meets the needs of end-users.
              </p>
              <p>
                Overall, I am a dedicated and experienced software developer who
                is committed to delivering results that exceed expectations. I
                am always looking for new opportunities to leverage my skills
                and contribute to exciting projects.
              </p>
              <p>
                In addition to my experience as a software developer, I have a
                deep passion for sports and outdoor activities. I love to spend
                my free time hiking through the mountains, exploring new trails,
                and pushing myself to new limits. When I&apos;m not on foot, I
                can often be found on my trusty bicycle, taking on long-distance
                rides with bags packed for bikepacking adventures.
              </p>
              <p>
                Shooting sports are also a hobby of mine, and I enjoy spending
                time at the range to improve my accuracy and technique. And when
                I&apos;m looking for something a bit more competitive, I love to
                hit the basketball court and challenge myself to improve my
                skills.
              </p>
              <p>
                My love for sports and outdoor activities has taught me the
                importance of discipline, perseverance, and teamwork. These are
                all qualities that I bring to my work as a software developer,
                helping me to stay focused, driven, and committed to delivering
                the best results possible.
              </p>
            </div>
          </div>
        </OddSection>
        <Section name="skills" setVisible={handleChangeVisibleSection}>
          <div tw=" align-middle justify-center">
            <SectionHeading>Skills</SectionHeading>
            <p tw="py-2">
              As software developer, with over a decade experience, I&apos;ve
              learned a lot of technologies. Here&apos;s a &apos;short&apos;
              <span
                role="img"
                aria-label="Emoji grinning Face with Sweat"
                aria-hidden={true}
              >
                😅
              </span>{' '}
              list, what I was using recently.
            </p>
            <Technologies />
          </div>
        </Section>
        <OddSection name="projects" setVisible={handleChangeVisibleSection}>
          <SectionHeading>Recent projects</SectionHeading>
          <RecentProjects />
        </OddSection>
        <Section name="hire_me" setVisible={handleChangeVisibleSection}>
          <HireMeHeading>#HIRE_ME</HireMeHeading>
          <div tw="flex flex-wrap">
            <div tw="basis-full mb-4 lg:(order-2 basis-2/5 mb-0) px-6 self-center">
              <p tw="py-4">
                Thank you for your interest in my profile. To access my resume,
                please fill out the form provided on this page.
              </p>
              <p tw="py-4">
                My resume provides a comprehensive overview of my professional
                experience, skills, and qualifications. It includes details
                about my work history, recent projects, and other relevant
                information that can help you evaluate my suitability for the
                position.
              </p>
              <p tw="py-4">
                I hope that my resume will provide you with the information you
                need to determine whether I am a good fit for the role. If you
                have any further questions or would like to discuss my
                application in more detail, please do not hesitate to contact
                me.
              </p>
              <p tw="py-4">
                Thank you for considering my application. I look forward to
                hearing from you soon.
              </p>
              <p tw="py-4 text-sm text-amber-500 dark:text-amber-300">
                To generate a GDPR statement, simply check the box provided on
                the form and click the &quot;Add GDPR Statement&quot; checkbox.
                The statement will be automatically added based on the
                information you have provided.
              </p>
            </div>
            <div tw="basis-full lg:(order-1 basis-3/5)  self-center">
              <ResumeGenerator />
            </div>
          </div>
        </Section>
        <OddSection name="contact" setVisible={handleChangeVisibleSection}>
          <SectionHeading>Contact</SectionHeading>
          <div tw="flex flex-wrap align-middle">
            <div tw="basis-full mb-4 lg:(order-2 basis-2/5 mb-0) px-6 self-center">
              <p tw="py-4">
                Thank you for your interest in reaching out to me. I am excited
                to learn more about the opportunities that you have available
                and to see if there is a good match between my skills and
                experience and your needs.
              </p>
              <p tw="py-4">
                If you could provide me with more information about your company
                and the position you are recruiting for, I would be happy to
                consider whether it is a good fit for me. Please feel free to
                reach out to me via email or phone, and I will be sure to
                respond as soon as possible.
              </p>
              <p tw="py-4">
                Thank you again for your interest, and I look forward to hearing
                from you soon.
              </p>
              <p tw="pt-4">Best regards,</p>
              <p tw="font-kalam text-xl text-blue-500 dark:text-blue-300">
                Luke Wawrzyniak
              </p>
            </div>
            <div tw="basis-full lg:(order-1 basis-3/5)  self-center">
              <ContactForm />
            </div>
          </div>
        </OddSection>
      </main>
    </Root>
  );
};

App.whyDidYouRender = true;

export default App;
